name: "Add coi-service-worker"

on:
  workflow_dispatch:
  push:
    branches:
      - godot3

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js ./coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' index.html

